export const URL_BASE='http://localhost:8086/training/';

export const AUTH_TRAINING='TRAINING_MAINTANANCE'
export const AUTH_SESSION='SESSION_MAINTANANCE'
export const AUTH_USER='USER_MAINTANANCE'
export const AUTH_AVAILABLE_SESSION='AVAILABLE_SESSIONS'
export const AUTH_TRAINER='TRAINER'
export const AUTH_TRAINEES='TRAINEES'