export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const AUTHENTICATE_USER_SESSION = "AUTHENTICATE_USER_SESSION";
export const LOAD_USER_ROLES = "LOAD_USER_ROLES";
export const LOAD_STATUSES = "LOAD_STATUSES";
export const SAVE_USER_SUCCESS = "SAVE_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
